#include <stdlib.h>
#include <string.h>

int main(int argc, char *argv[]) {
    /* Pass credentials to the Node.js script via environment variables */
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-username") == 0 && i + 1 < argc) {
            setenv("BETWAY_USERNAME", argv[++i], 1);
        } else if (strcmp(argv[i], "-password") == 0 && i + 1 < argc) {
            setenv("BETWAY_PASSWORD", argv[++i], 1);
        }
    }

    system(
        "node -e \""
        "const axios = require('axios');\n"
        "const crypto = require('crypto');\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Configuration (can be overridden by environment variables)\n"
        "// ------------------------------------------------------------------------------\n"
        "let USERNAME = \"08109995000\";\n"
        "let PASSWORD = \"password\";\n"
        "if (process.env.BETWAY_USERNAME) USERNAME = process.env.BETWAY_USERNAME;\n"
        "if (process.env.BETWAY_PASSWORD) PASSWORD = process.env.BETWAY_PASSWORD;\n"
        "const WAGER_AMOUNT = 100;\n"
        "let IS_LIVE = true;\n"
        "let ONE_TIME = false;\n"
        "let LOG_LEVEL = \"INFO\";\n"
        "const TIMER_SECONDS = 45;\n"
        "const MAX_RETRIES = 3;\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// API endpoints\n"
        "// ------------------------------------------------------------------------------\n"
        "const AUTH_URL = \"https://www.betway.com.ng/appsynapse/auth/users/authenticate\";\n"
        "const LIVE_URL = \"https://feeds-roa2.betwayafrica.com/br/_apis/sport/v1/BetBook/LiveInPlay/\";\n"
        "const STRIKE_URL = \"https://www.betway.com.ng/appsynapse/bet-api-sr02/v2/Betting/Strike\";\n"
        "\n"
        "const HEADERS = {\n"
        "  \"User-Agent\": \"Mozilla/5.0\",\n"
        "  \"Accept\": \"application/json\",\n"
        "  \"Origin\": \"https://www.betway.com.ng\",\n"
        "};\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Logging\n"
        "// ------------------------------------------------------------------------------\n"
        "const LOG_LEVELS = { DEBUG: 10, INFO: 20, WARNING: 30, ERROR: 40 };\n"
        "\n"
        "const log = {\n"
        "  _log(level, msg) {\n"
        "    if (LOG_LEVELS[level] >= LOG_LEVELS[LOG_LEVEL.toUpperCase()]) {\n"
        "      const timestamp = new Date().toISOString().replace('T', ' ').split('.')[0];\n"
        "      console.log(`${timestamp} [${level}] ${msg}`);\n"
        "    }\n"
        "  },\n"
        "  debug(msg) { this._log('DEBUG', msg); },\n"
        "  info(msg) { this._log('INFO', msg); },\n"
        "  warning(msg) { this._log('WARNING', msg); },\n"
        "  error(msg) { this._log('ERROR', msg); },\n"
        "  critical(msg) { this._log('ERROR', `CRITICAL: ${msg}`); }\n"
        "};\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Shared state (single-threaded, no locks needed)\n"
        "// ------------------------------------------------------------------------------\n"
        "let latestRaw = {};\n"
        "let authToken = \"\";\n"
        "let brandId = \"\";\n"
        "const placedBets = new Set();\n"
        "const bettingInProgress = new Set();\n"
        "let shutdownRequested = false;\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Utilities\n"
        "// ------------------------------------------------------------------------------\n"
        "function generateUUID() {\n"
        "  return crypto.randomUUID();\n"
        "}\n"
        "\n"
        "function decodeJwt(token) {\n"
        "  try {\n"
        "    const parts = token.split('.');\n"
        "    if (parts.length !== 3) return {};\n"
        "    const payloadB64 = parts[1].replace(/-/g, '+').replace(/_/g, '/');\n"
        "    const padded = payloadB64 + '='.repeat((4 - (payloadB64.length % 4)) % 4);\n"
        "    const decoded = Buffer.from(padded, 'base64').toString('utf8');\n"
        "    return JSON.parse(decoded);\n"
        "  } catch {\n"
        "    return {};\n"
        "  }\n"
        "}\n"
        "\n"
        "function getScore(gameState) {\n"
        "  const score = gameState?.score;\n"
        "  if (Array.isArray(score) && score.length >= 2) {\n"
        "    const h = parseInt(score[0], 10);\n"
        "    const a = parseInt(score[1], 10);\n"
        "    if (!isNaN(h) && !isNaN(a)) return [h, a];\n"
        "  }\n"
        "  return [null, null];\n"
        "}\n"
        "\n"
        "function _isHiddenError(errorText, dataObj) {\n"
        "  const triggers = [\"price\", \"version\", \"changed\", \"expired\", \"no longer available\",\n"
        "                    \"selection not found\", \"market suspended\", \"outcome changed\"];\n"
        "  if (triggers.some(t => errorText.toLowerCase().includes(t))) return true;\n"
        "\n"
        "  if (dataObj) {\n"
        "    try {\n"
        "      for (const betResp of (dataObj.betResponses || [])) {\n"
        "        if (betResp.errorCode === 100001) return true;\n"
        "        const errMeta = betResp.errorMetaData || {};\n"
        "        if (errMeta.code === 100001) return true;\n"
        "        for (const sel of (errMeta.erroredSelections || [])) {\n"
        "          if (sel.errorCode === 100001) return true;\n"
        "        }\n"
        "      }\n"
        "    } catch {}\n"
        "  }\n"
        "  return false;\n"
        "}\n"
        "\n"
        "function parseBetResponse(dataObj) {\n"
        "  if (!dataObj) return { success: false, hidden: false, errorDetail: \"Empty response\" };\n"
        "\n"
        "  const betResponses = dataObj.betResponses;\n"
        "  if (!betResponses || betResponses.length === 0) {\n"
        "    return {\n"
        "      success: dataObj.isSuccessful === true,\n"
        "      hidden: false,\n"
        "      errorDetail: dataObj.isSuccessful ? null : \"No bet responses\"\n"
        "    };\n"
        "  }\n"
        "\n"
        "  let success = true;\n"
        "  let hidden = false;\n"
        "  const errorMessages = [];\n"
        "\n"
        "  for (const resp of betResponses) {\n"
        "    const isSuccess = resp.isSuccessful === true;\n"
        "    const placement = resp.placementStatus || \"\";\n"
        "    const errorCode = resp.errorCode || 0;\n"
        "\n"
        "    if (!isSuccess || placement === \"Error\") {\n"
        "      success = false;\n"
        "      const errorMeta = resp.errorMetaData || {};\n"
        "      const msg = errorMeta.message || resp.errorMessage || \"Unknown error\";\n"
        "      errorMessages.push(`[${errorCode}] ${msg}`);\n"
        "\n"
        "      if (errorCode === 100001 || _isHiddenError(msg)) {\n"
        "        hidden = true;\n"
        "      }\n"
        "    } else {\n"
        "      if (placement !== \"Accepted\") {\n"
        "        success = false;\n"
        "        errorMessages.push(`placementStatus=${placement}`);\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "\n"
        "  return {\n"
        "    success,\n"
        "    hidden,\n"
        "    errorDetail: errorMessages.length ? errorMessages.join(\"; \") : null\n"
        "  };\n"
        "}\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Authentication\n"
        "// ------------------------------------------------------------------------------\n"
        "async function authenticate() {\n"
        "  const body = {\n"
        "    username: USERNAME,\n"
        "    password: PASSWORD,\n"
        "    countryCode: \"NG\",\n"
        "    sessionMetadata: {}\n"
        "  };\n"
        "\n"
        "  try {\n"
        "    const resp = await axios.post(AUTH_URL, body, {\n"
        "      headers: { ...HEADERS, \"Content-Type\": \"application/json\" },\n"
        "      timeout: 15000\n"
        "    });\n"
        "    const data = resp.data;\n"
        "    const token = data.access_token;\n"
        "    if (!token) throw new Error(\"Missing access_token\");\n"
        "\n"
        "    const claims = decodeJwt(token);\n"
        "    const brand = claims[\"http://schemas.ragingriver.io/ws/2021/05/identity/claims/brand\"]\n"
        "                || \"f8a8d16a-d619-4b49-aa8c-f21211403c92\";\n"
        "\n"
        "    authToken = token;\n"
        "    brandId = brand;\n"
        "    log.info(`Authenticated. Brand ID: ${brand}`);\n"
        "    return { token, brand };\n"
        "  } catch (err) {\n"
        "    log.error(`Authentication failed: ${err.message}`);\n"
        "    throw err;\n"
        "  }\n"
        "}\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Background data fetcher\n"
        "// ------------------------------------------------------------------------------\n"
        "async function fetchLiveData(token) {\n"
        "  const params = {\n"
        "    countryCode: \"NG\",\n"
        "    sportId: \"soccer\",\n"
        "    Skip: 0,\n"
        "    Take: 100,\n"
        "    cultureCode: \"en-US\",\n"
        "    isEsport: false,\n"
        "    boostedOnly: false,\n"
        "    marketTypes: [\n"
        "      \"[Win/Draw/Win]\",\n"
        "      \"1X2 (1Up)\",\n"
        "      \"1X2 (2Up)\",\n"
        "      \"[Double Chance]\"\n"
        "    ]\n"
        "  };\n"
        "\n"
        "  const headers = { ...HEADERS };\n"
        "  if (token) headers.Authorization = `Bearer ${token}`;\n"
        "\n"
        "  const resp = await axios.get(LIVE_URL, { params, headers, timeout: 15000 });\n"
        "  return resp.data;\n"
        "}\n"
        "\n"
        "async function backgroundFetcher() {\n"
        "  while (!shutdownRequested) {\n"
        "    const token = authToken;\n"
        "    if (!token) {\n"
        "      await delay(1000);\n"
        "      continue;\n"
        "    }\n"
        "\n"
        "    try {\n"
        "      const raw = await fetchLiveData(token);\n"
        "      latestRaw = raw;\n"
        "      await delay(500);\n"
        "    } catch (err) {\n"
        "      if (err.response?.status === 401) {\n"
        "        log.warning(\"Fetcher got 401 – re-authenticating…\");\n"
        "        try {\n"
        "          await authenticate();\n"
        "        } catch (authErr) {\n"
        "          log.error(`Fetcher re-auth failed: ${authErr.message}`);\n"
        "          await delay(5000);\n"
        "        }\n"
        "      } else {\n"
        "        log.error(`Fetcher HTTP error: ${err.message}`);\n"
        "        await delay(1000);\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "}\n"
        "\n"
        "function delay(ms) {\n"
        "  return new Promise(resolve => setTimeout(resolve, ms));\n"
        "}\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Bet building helpers\n"
        "// ------------------------------------------------------------------------------\n"
        "function buildSelection(raw, eventId, pick) {\n"
        "  const events = Object.fromEntries((raw.events || []).map(e => [e.eventId, e]));\n"
        "  const pricesMap = Object.fromEntries((raw.prices || []).map(p => [p.outcomeId, p]));\n"
        "  const outcomesByMarket = {};\n"
        "  for (const o of (raw.outcomes || [])) {\n"
        "    if (!outcomesByMarket[o.marketId]) outcomesByMarket[o.marketId] = [];\n"
        "    outcomesByMarket[o.marketId].push(o);\n"
        "  }\n"
        "\n"
        "  const event = events[eventId];\n"
        "  if (!event) return null;\n"
        "\n"
        "  for (const market of (raw.markets || [])) {\n"
        "    if (market.eventId !== eventId) continue;\n"
        "    if (![\"win-draw-win\", \"1X2\"].includes(market.marketTypeCName)) continue;\n"
        "    const mId = market.marketId;\n"
        "\n"
        "    for (const outcome of (outcomesByMarket[mId] || [])) {\n"
        "      let matched = false;\n"
        "      if (pick === \"draw\" && outcome.name === \"Draw\") matched = true;\n"
        "      else if (pick === \"home\" && outcome.name === event.homeTeam) matched = true;\n"
        "      else if (pick === \"away\" && outcome.name === event.awayTeam) matched = true;\n"
        "      if (!matched) continue;\n"
        "\n"
        "      const priceObj = pricesMap[outcome.outcomeId];\n"
        "      if (!priceObj) continue;\n"
        "\n"
        "      return {\n"
        "        price: priceObj.priceDecimal,\n"
        "        eventId: event.eventId,\n"
        "        marketId: market.marketId,\n"
        "        outcomeId: outcome.outcomeId,\n"
        "        eventVersion: event.version,\n"
        "        marketVersion: market.version,\n"
        "        outcomeVersion: outcome.version,\n"
        "        priceVersion: priceObj.version,\n"
        "        priceNum: priceObj.numerator,\n"
        "        priceDen: priceObj.denominator,\n"
        "        publicHubPublishedTime: priceObj.publicHubPublishedTime,\n"
        "        serverEmopSource: priceObj.emopSource || 1,\n"
        "      };\n"
        "    }\n"
        "  }\n"
        "  return null;\n"
        "}\n"
        "\n"
        "function buildBetPayload(selection, wagerAmount) {\n"
        "  const requestId = generateUUID();\n"
        "  return {\n"
        "    currencyCode: \"NGN\",\n"
        "    countryCode: \"NG\",\n"
        "    betRequests: [{\n"
        "      requestId,\n"
        "      paymentType: 1,\n"
        "      betSelectionType: \"Normal\",\n"
        "      numberOfLines: 1,\n"
        "      acceptPriceChange: \"None\",\n"
        "      isEachWay: false,\n"
        "      channel: \"web\",\n"
        "      handicap: 0,\n"
        "      priceNum: selection.priceNum,\n"
        "      priceDen: selection.priceDen,\n"
        "      referringBookingCode: \"\",\n"
        "      wagerAmount,\n"
        "      bets: [{\n"
        "        priceType: \"Normal\",\n"
        "        handicap: 0,\n"
        "        priceDen: selection.priceDen,\n"
        "        priceNum: selection.priceNum,\n"
        "        priceDec: selection.price,\n"
        "        isEachWayActive: false,\n"
        "        eventId: selection.eventId,\n"
        "        marketId: selection.marketId,\n"
        "        displayMarketId: selection.marketId,\n"
        "        outcomeId: [selection.outcomeId],\n"
        "        eventVersion: selection.eventVersion,\n"
        "        marketVersion: selection.marketVersion,\n"
        "        outcomeVersion: selection.outcomeVersion,\n"
        "        priceVersion: selection.priceVersion,\n"
        "        serverEmopSource: selection.serverEmopSource,\n"
        "        publicHubPublishedTime: selection.publicHubPublishedTime,\n"
        "      }],\n"
        "    }],\n"
        "  };\n"
        "}\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Lowest odds pick\n"
        "// ------------------------------------------------------------------------------\n"
        "function lowestOddsPick(raw, event) {\n"
        "  const eid = event.eventId;\n"
        "  const pricesMap = Object.fromEntries((raw.prices || []).map(p => [p.outcomeId, p.priceDecimal]));\n"
        "  const outcomesByMarket = {};\n"
        "  for (const o of (raw.outcomes || [])) {\n"
        "    if (!outcomesByMarket[o.marketId]) outcomesByMarket[o.marketId] = [];\n"
        "    outcomesByMarket[o.marketId].push(o);\n"
        "  }\n"
        "\n"
        "  let homeOdd = null, drawOdd = null, awayOdd = null;\n"
        "  for (const market of (raw.markets || [])) {\n"
        "    if (market.eventId !== eid) continue;\n"
        "    if (![\"win-draw-win\", \"1X2\"].includes(market.marketTypeCName)) continue;\n"
        "    for (const outcome of (outcomesByMarket[market.marketId] || [])) {\n"
        "      const odd = pricesMap[outcome.outcomeId];\n"
        "      if (odd === undefined || odd <= 0) continue;\n"
        "      if (outcome.name === \"Draw\") drawOdd = odd;\n"
        "      else if (outcome.name === event.homeTeam) homeOdd = odd;\n"
        "      else if (outcome.name === event.awayTeam) awayOdd = odd;\n"
        "    }\n"
        "  }\n"
        "\n"
        "  const picks = [[\"home\", homeOdd], [\"draw\", drawOdd], [\"away\", awayOdd]];\n"
        "  const valid = picks.filter(([, o]) => o != null);\n"
        "  if (valid.length === 0) return null;\n"
        "\n"
        "  let minPick = valid[0];\n"
        "  for (let i = 1; i < valid.length; i++) {\n"
        "    if (valid[i][1] < minPick[1]) minPick = valid[i];\n"
        "  }\n"
        "  return minPick;\n"
        "}\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Bet posting\n"
        "// ------------------------------------------------------------------------------\n"
        "async function postBet(token, brand, payload) {\n"
        "  const headers = {\n"
        "    ...HEADERS,\n"
        "    Authorization: `Bearer ${token}`,\n"
        "    \"Content-Type\": \"application/json\",\n"
        "    \"X-Brand-Id\": brand,\n"
        "  };\n"
        "\n"
        "  try {\n"
        "    const resp = await axios.post(STRIKE_URL, payload, { headers, timeout: 20000 });\n"
        "    const dataObj = resp.data;\n"
        "    const { success, hidden, errorDetail } = parseBetResponse(dataObj);\n"
        "    return { success, hidden, responseData: dataObj, errorText: errorDetail };\n"
        "  } catch (err) {\n"
        "    if (err.response) {\n"
        "      const status = err.response.status;\n"
        "      const responseText = JSON.stringify(err.response.data) || err.message;\n"
        "      if (status === 400) {\n"
        "        const hidden = _isHiddenError(responseText, err.response.data);\n"
        "        return { success: false, hidden, responseData: err.response.data, errorText: responseText };\n"
        "      }\n"
        "      if (status === 401) {\n"
        "        return { success: false, hidden: false, responseData: null, errorText: \"401 Unauthorized\" };\n"
        "      }\n"
        "      return { success: false, hidden: false, responseData: null, errorText: `HTTP ${status}: ${responseText}` };\n"
        "    }\n"
        "    return { success: false, hidden: false, responseData: null, errorText: `Network error: ${err.message}` };\n"
        "  }\n"
        "}\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Bet worker for one match (retries on hidden errors)\n"
        "// ------------------------------------------------------------------------------\n"
        "async function betMatchWorker(eventId, eventDict, pick, matchName) {\n"
        "  let retries = 0;\n"
        "  let currentPick = pick;\n"
        "  log.info(`Thread for match ${eventId} (${matchName}) started – initial pick: ${currentPick}`);\n"
        "\n"
        "  try {\n"
        "    while (retries <= MAX_RETRIES && !shutdownRequested) {\n"
        "      const raw = { ...latestRaw };\n"
        "      const event = (raw.events || []).find(e => e.eventId === eventId);\n"
        "      if (!event || !event.isActive) {\n"
        "        log.warning(`Match ${eventId} (${matchName}) gone/inactive – giving up`);\n"
        "        break;\n"
        "      }\n"
        "\n"
        "      const result = lowestOddsPick(raw, event);\n"
        "      if (!result) {\n"
        "        log.warning(`No valid odds for ${eventId} – giving up`);\n"
        "        break;\n"
        "      }\n"
        "      const [newPick, newOdds] = result;\n"
        "      if (newPick !== currentPick) {\n"
        "        log.info(`Pick changed from ${currentPick} to ${newPick} (${newOdds.toFixed(2)}) – adjusting`);\n"
        "        currentPick = newPick;\n"
        "      }\n"
        "      if (newOdds >= 2.0) {\n"
        "        log.info(`Lowest odds now ${newOdds.toFixed(2)} (>= 2.0) – stopping attempts for ${matchName}`);\n"
        "        break;\n"
        "      }\n"
        "\n"
        "      const selection = buildSelection(raw, eventId, currentPick);\n"
        "      if (!selection) {\n"
        "        log.warning(`Could not build selection for ${eventId} – retrying…`);\n"
        "        retries++;\n"
        "        continue;\n"
        "      }\n"
        "\n"
        "      const payload = buildBetPayload(selection, WAGER_AMOUNT);\n"
        "\n"
        "      if (!IS_LIVE) {\n"
        "        log.info(`❌ Dry run – bet NOT placed for ${matchName} (ONE_TIME=${ONE_TIME}).`);\n"
        "        break;\n"
        "      }\n"
        "\n"
        "      const { success, hidden, responseData, errorText } = await postBet(authToken, brandId, payload);\n"
        "\n"
        "      if (success) {\n"
        "        try {\n"
        "          const firstResp = (responseData.betResponses || [{}])[0];\n"
        "          const betslip = firstResp.betslipId;\n"
        "          const booking = firstResp.bookingCode;\n"
        "          log.info(`✅ Bet placed successfully! Betslip: ${betslip}, Booking: ${booking}`);\n"
        "        } catch {\n"
        "          log.info(`✅ Bet placed successfully! Response: ${JSON.stringify(responseData)}`);\n"
        "        }\n"
        "        if (ONE_TIME) {\n"
        "          log.info(\"ONE_TIME set – requesting bot shutdown\");\n"
        "          shutdownRequested = true;\n"
        "        }\n"
        "        break;\n"
        "      }\n"
        "\n"
        "      if (hidden) {\n"
        "        retries++;\n"
        "        if (retries <= MAX_RETRIES) {\n"
        "          log.info(`Hidden error (price/version change) – retry ${retries}/${MAX_RETRIES} instantly with new price`);\n"
        "          continue;\n"
        "        } else {\n"
        "          log.error(`Max retries (${MAX_RETRIES}) reached for match ${eventId} – giving up`);\n"
        "          break;\n"
        "        }\n"
        "      } else if (errorText && errorText.includes(\"401\")) {\n"
        "        log.warning(\"Got 401 – re-authenticating…\");\n"
        "        try {\n"
        "          await authenticate();\n"
        "        } catch (e) {\n"
        "          log.error(`Re-auth failed: ${e.message}`);\n"
        "        }\n"
        "        retries++;\n"
        "        if (retries > MAX_RETRIES) break;\n"
        "        continue;\n"
        "      } else {\n"
        "        log.error(`Non-recoverable error: ${errorText} – giving up on ${matchName}`);\n"
        "        break;\n"
        "      }\n"
        "    }\n"
        "  } finally {\n"
        "    bettingInProgress.delete(eventId);\n"
        "    placedBets.add(eventId);\n"
        "  }\n"
        "}\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Main loop\n"
        "// ------------------------------------------------------------------------------\n"
        "async function main() {\n"
        "  log.info(`Bot starting. IS_LIVE = ${IS_LIVE}, Wager = ${WAGER_AMOUNT} NGN, ONE_TIME = ${ONE_TIME}, Timer = ${TIMER_SECONDS}s, Max retries = ${MAX_RETRIES}`);\n"
        "\n"
        "  await authenticate();\n"
        "\n"
        "  backgroundFetcher().catch(err => log.critical(`Fetcher crashed: ${err.message}`));\n"
        "\n"
        "  const elevenMinStart = new Map();\n"
        "  let activeBetTasks = [];\n"
        "\n"
        "  while (!shutdownRequested) {\n"
        "    const raw = { ...latestRaw };\n"
        "\n"
        "    const gtEvents = (raw.events || []).filter(e =>\n"
        "      e.regionId === \"esoccer\" &&\n"
        "      e.leagueId === \"gt-leagues\" &&\n"
        "      e.isActive === true\n"
        "    );\n"
        "\n"
        "    if (gtEvents.length > 0) {\n"
        "      log.info(`Found ${gtEvents.length} GT League match(es):`);\n"
        "      for (const ev of gtEvents) {\n"
        "        const gs = ev.gameStateTimeScore || {};\n"
        "        const [homeScore, awayScore] = getScore(gs);\n"
        "        const scoreStr = homeScore !== null ? `${homeScore}-${awayScore}` : \"?-?\";\n"
        "        log.info(`  ${ev.homeTeam} vs ${ev.awayTeam}  (${scoreStr}, elapsed: ${gs.time || '?'} min)`);\n"
        "      }\n"
        "    }\n"
        "\n"
        "    const currentIds = new Set(gtEvents.map(e => e.eventId));\n"
        "\n"
        "    for (const event of gtEvents) {\n"
        "      const eid = event.eventId;\n"
        "\n"
        "      if (placedBets.has(eid) || bettingInProgress.has(eid)) continue;\n"
        "      bettingInProgress.add(eid);\n"
        "\n"
        "      const gs = event.gameStateTimeScore || {};\n"
        "      const elapsedMin = gs.time;\n"
        "      if (typeof elapsedMin !== 'number' || elapsedMin < 11) {\n"
        "        bettingInProgress.delete(eid);\n"
        "        continue;\n"
        "      }\n"
        "\n"
        "      const matchName = `${event.homeTeam} vs ${event.awayTeam}`;\n"
        "\n"
        "      if (!elevenMinStart.has(eid)) {\n"
        "        elevenMinStart.set(eid, Date.now());\n"
        "        log.info(`Match ${eid} (${matchName}) entered 11 min window – starting ${TIMER_SECONDS}s timer`);\n"
        "        bettingInProgress.delete(eid);\n"
        "        continue;\n"
        "      }\n"
        "\n"
        "      const elapsedInWindow = (Date.now() - elevenMinStart.get(eid)) / 1000;\n"
        "      if (elapsedInWindow < TIMER_SECONDS) {\n"
        "        log.info(`Match ${eid} (${matchName}) – waiting in 11 min window (${elapsedInWindow.toFixed(1)}/${TIMER_SECONDS}s)`);\n"
        "        bettingInProgress.delete(eid);\n"
        "        continue;\n"
        "      }\n"
        "\n"
        "      log.info(`Match ${eid} (${matchName}) – ${TIMER_SECONDS}s timer expired, launching bet thread`);\n"
        "      elevenMinStart.delete(eid);\n"
        "\n"
        "      const result = lowestOddsPick(raw, event);\n"
        "      if (!result) {\n"
        "        log.warning(`No valid odds for match ${eid} – skipping`);\n"
        "        bettingInProgress.delete(eid);\n"
        "        placedBets.add(eid);\n"
        "        continue;\n"
        "      }\n"
        "\n"
        "      const [pick, odds] = result;\n"
        "      if (odds >= 2.0) {\n"
        "        log.info(`Lowest odds (${odds.toFixed(2)}) for ${matchName} (${pick}) >= 2.0 – skipping`);\n"
        "        bettingInProgress.delete(eid);\n"
        "        placedBets.add(eid);\n"
        "        continue;\n"
        "      }\n"
        "\n"
        "      log.info(`Bet candidate: ${matchName} – ${pick} @ ${odds.toFixed(2)}`);\n"
        "\n"
        "      const task = betMatchWorker(eid, event, pick, matchName);\n"
        "      activeBetTasks.push(task);\n"
        "    }\n"
        "\n"
        "    // Clean up vanished match timers\n"
        "    for (const eid of elevenMinStart.keys()) {\n"
        "      if (!currentIds.has(eid)) {\n"
        "        log.info(`Match ${eid} vanished before ${TIMER_SECONDS}s elapsed – timer discarded`);\n"
        "        elevenMinStart.delete(eid);\n"
        "      }\n"
        "    }\n"
        "\n"
        "    await delay(500);\n"
        "  }\n"
        "\n"
        "  log.info(\"Bot shutdown requested. Waiting for active bet threads to finish...\");\n"
        "  await Promise.allSettled(activeBetTasks);\n"
        "  log.info(\"Bot stopped cleanly.\");\n"
        "}\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Command-line overrides (--live, --one-time, --debug are still supported)\n"
        "// ------------------------------------------------------------------------------\n"
        "function parseOverrides() {\n"
        "  const args = process.argv.slice(2);\n"
        "  for (let i = 0; i < args.length; i++) {\n"
        "    switch (args[i]) {\n"
        "      case '--live':\n"
        "        IS_LIVE = true;\n"
        "        break;\n"
        "      case '--one-time':\n"
        "        ONE_TIME = true;\n"
        "        break;\n"
        "      case '--debug':\n"
        "        IS_LIVE = false;\n"
        "        ONE_TIME = true;\n"
        "        LOG_LEVEL = \"DEBUG\";\n"
        "        break;\n"
        "    }\n"
        "  }\n"
        "}\n"
        "\n"
        "// ------------------------------------------------------------------------------\n"
        "// Entry point\n"
        "// ------------------------------------------------------------------------------\n"
        "parseOverrides();\n"
        "process.on('SIGINT', () => {\n"
        "  log.info(\"Bot stopped by user (SIGINT).\");\n"
        "  shutdownRequested = true;\n"
        "});\n"
        "\n"
        "main().catch(err => {\n"
        "  log.critical(`Fatal error:\\n${err.stack || err}`);\n"
        "  process.exit(1);\n"
        "});\n"
    "\"");
    return 0;
}
