name: Build Binaries

on:
  workflow_dispatch:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: |
          pip install cython

      - run: |
          cython --embed -3 live.py -o lib.c

      - run: |
          gcc lib.c -o lib \
            $(python3-config --cflags --embed --ldflags)

      - uses: actions/upload-artifact@v4
        with:
          name: linux-files
          path: |
            lib
            lib.c

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: |
          pip install cython

      - run: |
          cython --embed -3 live.py -o lib.c

      - uses: ilammy/msvc-dev-cmd@v1

      - shell: cmd
        run: |
          cl /O2 /EHsc lib.c ^
            /I "%Python_ROOT_DIR%\include" ^
            /link /LIBPATH:"%Python_ROOT_DIR%\libs" ^
            /OUT:lib.exe

      - uses: actions/upload-artifact@v4
        with:
          name: windows-files
          path: |
            lib.exe
            lib.c

  package:
    needs:
      - build-linux
      - build-windows

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

      - run: |
          mkdir release

          cp linux-files/lib release/lib
          cp linux-files/lib.c release/lib.c
          cp windows-files/lib.exe release/lib.exe

          cd release
          zip -r lib-package.zip *

      - uses: actions/upload-artifact@v4
        with:
          name: lib-package
          path: release/lib-package.zip
