name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libcjson-dev uuid-dev libssl-dev

    - name: Download uthash (header‑only library)
      run: |
        mkdir -p include
        wget -q -O include/uthash.h \
          "https://raw.githubusercontent.com/troydhanson/uthash/master/src/uthash.h"

    - name: Build
      run: make

    - name: Export binary
      uses: actions/upload-artifact@v4
      with:
        name: liver
        path: liver
        retention-days: 5
